
title: Tensor Computation for Data Processing
description: >
    IJCAI-ECAI 2022 Tutorial 
    <br><br>
    Day: Sat, July 23  
    <br>
    Time: A1, A2
    <br>
    Location: Schubert 3
    
theme: jekyll-theme-cayman
